// Country reference. All of this is baked in — no network, no lookups.
//
// General guidance, not gospel: tipping customs vary by region and by how fancy
// the place is, and emergency numbers do occasionally change. 112 reaches
// emergency services across the whole EU and is the safe default everywhere here.

export const COUNTRIES = [
  {
    code: 'PL', eea: true, tz: 'Europe/Warsaw', name: 'Poland', flag: '🇵🇱', langs: ['pl'],
    currency: { code: 'PLN', symbol: 'zł', name: 'Polish złoty' },
    emergency: { general: '112', police: '997', fire: '998', ambulance: '999' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, E' },
    tipping: 'Around 10% in restaurants. Say the total you want to pay when handing over the card — saying "thank you" as they take it can mean "keep the change".',
    water: 'Tap water is safe.',
    driving: 'right',
    notes: 'Cards accepted almost everywhere, including small shops. BLIK is the local phone-payment standard.',
  },
  {
    code: 'DE', eea: true, tz: 'Europe/Berlin', name: 'Germany', flag: '🇩🇪', langs: ['de'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '110', fire: '112', ambulance: '112' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Round up or add 5–10%. Tell the server the total rather than leaving coins on the table.',
    water: 'Tap water is safe, though restaurants will assume you want bottled.',
    driving: 'right',
    notes: 'Carry cash — plenty of bakeries, bars and kiosks still refuse cards. Shops shut on Sundays. Bottle deposit (Pfand) is refunded at supermarket machines.',
  },
  {
    code: 'CZ', eea: true, tz: 'Europe/Prague', name: 'Czechia', flag: '🇨🇿', langs: ['cs'],
    currency: { code: 'CZK', symbol: 'Kč', name: 'Czech koruna' },
    emergency: { general: '112', police: '158', fire: '150', ambulance: '155' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, E' },
    tipping: 'Round up or about 10%.',
    water: 'Tap water is safe.',
    driving: 'right',
    notes: 'Not on the euro despite the EU membership — refuse euro prices in tourist spots, the rate will be terrible. Avoid street currency exchange booths.',
  },
  {
    code: 'AT', eea: true, tz: 'Europe/Vienna', name: 'Austria', flag: '🇦🇹', langs: ['de'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '133', fire: '122', ambulance: '144' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Round up or 5–10%.',
    water: 'Excellent — much of it comes straight from the Alps.',
    driving: 'right',
    notes: 'Motorways need a vignette sticker. Shops shut on Sundays.',
  },
  {
    code: 'SK', eea: true, tz: 'Europe/Bratislava', name: 'Slovakia', flag: '🇸🇰', langs: ['cs'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '158', fire: '150', ambulance: '155' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, E' },
    tipping: 'Around 10%.',
    water: 'Tap water is safe.',
    driving: 'right',
    notes: 'Czech is widely understood, and Polish often is too.',
  },
  {
    code: 'NL', eea: true, tz: 'Europe/Amsterdam', name: 'Netherlands', flag: '🇳🇱', langs: ['nl'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '112', fire: '112', ambulance: '112' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Service is included. Round up if you liked it.',
    water: 'Tap water is safe.',
    driving: 'right',
    notes: 'Many places take only Maestro/debit, not credit cards — check before ordering. Watch for bike lanes; cyclists have priority and will not stop.',
  },
  {
    code: 'FR', eea: true, tz: 'Europe/Paris', name: 'France', flag: '🇫🇷', langs: ['fr'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '17', fire: '18', ambulance: '15' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, E' },
    tipping: 'Service is legally included (service compris). Leaving a couple of euros is generous, not expected.',
    water: 'Tap water is safe. Ask for "une carafe d\'eau" and it is free.',
    driving: 'right',
    notes: 'Greeting with "bonjour" before anything else genuinely changes how you are treated.',
  },
  {
    code: 'IT', eea: true, tz: 'Europe/Rome', name: 'Italy', flag: '🇮🇹', langs: ['it'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '113', fire: '115', ambulance: '118' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F, L' },
    tipping: 'Not expected. A cover charge (coperto) is usually on the bill already.',
    water: 'Tap water is safe. Public fountains in Rome are drinkable.',
    driving: 'right',
    notes: 'Standing at the bar is cheaper than sitting down — sometimes by a lot. Historic centres have camera-enforced driving zones (ZTL) with automatic fines.',
  },
  {
    code: 'ES', eea: true, tz: 'Europe/Madrid', name: 'Spain', flag: '🇪🇸', langs: ['es'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '091', fire: '080', ambulance: '061' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Small change is plenty. Not expected.',
    water: 'Tap water is safe, though the taste varies a lot by region.',
    driving: 'right',
    notes: 'Lunch runs late (14:00) and dinner much later (21:00+). Many shops close mid-afternoon.',
  },
  {
    code: 'CH', eea: false, tz: 'Europe/Zurich', name: 'Switzerland', flag: '🇨🇭', langs: ['de', 'fr', 'it'],
    currency: { code: 'CHF', symbol: 'Fr.', name: 'Swiss franc' },
    emergency: { general: '112', police: '117', fire: '118', ambulance: '144' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, J' },
    tipping: 'Included. Round up if you want.',
    water: 'Excellent, including most public fountains.',
    driving: 'right',
    notes: 'Not in the EU, so roaming may be charged separately — check before you cross. Expensive. Swiss plugs (type J) are narrower than the usual F, so an F plug may not fit.',
  },
  {
    code: 'GB', eea: false, tz: 'Europe/London', name: 'United Kingdom', flag: '🇬🇧', langs: ['en'],
    currency: { code: 'GBP', symbol: '£', name: 'Pound sterling' },
    emergency: { general: '999', police: '999', fire: '999', ambulance: '999' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'G' },
    tipping: '10–12.5%, often already added as a "service charge". Do not tip twice.',
    water: 'Tap water is safe.',
    driving: 'left',
    notes: '112 also works. Type G plugs are unlike anything on the continent — you need a specific adapter.',
  },
  {
    code: 'HU', eea: true, tz: 'Europe/Budapest', name: 'Hungary', flag: '🇭🇺', langs: ['en'],
    currency: { code: 'HUF', symbol: 'Ft', name: 'Hungarian forint' },
    emergency: { general: '112', police: '107', fire: '105', ambulance: '104' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Around 10%. Check whether a service charge is already on the bill.',
    water: 'Tap water is safe.',
    driving: 'right',
    notes: 'Not on the euro. Motorways need an e-vignette bought in advance.',
  },
  {
    code: 'HR', eea: true, tz: 'Europe/Zagreb', name: 'Croatia', flag: '🇭🇷', langs: ['en'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '192', fire: '193', ambulance: '194' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Round up or about 10%.',
    water: 'Tap water is safe.',
    driving: 'right',
    notes: 'Switched to the euro in 2023 — old kuna prices in guidebooks are out of date.',
  },
  {
    code: 'SE', eea: true, tz: 'Europe/Stockholm', name: 'Sweden', flag: '🇸🇪', langs: ['sv'],
    currency: { code: 'SEK', symbol: 'kr', name: 'Swedish krona' },
    emergency: { general: '112', police: '112', fire: '112', ambulance: '112' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Included. Not expected.',
    water: 'Excellent.',
    driving: 'right',
    notes: 'Close to cashless — many places refuse cash outright. Bring a card that works.',
  },
  {
    code: 'DK', eea: true, tz: 'Europe/Copenhagen', name: 'Denmark', flag: '🇩🇰', langs: ['en'],
    currency: { code: 'DKK', symbol: 'kr', name: 'Danish krone' },
    emergency: { general: '112', police: '114', fire: '112', ambulance: '112' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, E, F, K' },
    tipping: 'Included. Not expected.',
    water: 'Excellent.',
    driving: 'right',
    notes: 'Largely cashless. 114 is the non-emergency police line.',
  },
  {
    code: 'NO', eea: true, tz: 'Europe/Oslo', name: 'Norway', flag: '🇳🇴', langs: ['en'],
    currency: { code: 'NOK', symbol: 'kr', name: 'Norwegian krone' },
    emergency: { general: '112', police: '112', fire: '110', ambulance: '113' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Included. Not expected.',
    water: 'Excellent.',
    driving: 'right',
    notes: 'Not in the EU, so roaming rules differ. Very expensive.',
  },
  {
    code: 'BE', eea: true, tz: 'Europe/Brussels', name: 'Belgium', flag: '🇧🇪', langs: ['nl', 'fr'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '101', fire: '112', ambulance: '112' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, E' },
    tipping: 'Included. Round up if you want.',
    water: 'Tap water is safe.',
    driving: 'right',
    notes: 'Dutch in the north, French in the south, German in a small eastern strip. Guessing wrong can land badly — English is the safe neutral choice.',
  },
  {
    code: 'SI', eea: true, tz: 'Europe/Ljubljana', name: 'Slovenia', flag: '🇸🇮', langs: ['en'],
    currency: { code: 'EUR', symbol: '€', name: 'Euro' },
    emergency: { general: '112', police: '113', fire: '112', ambulance: '112' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Round up or about 10%.',
    water: 'Excellent.',
    driving: 'right',
    notes: 'Motorways need a vignette.',
  },
  {
    code: 'UA', eea: false, tz: 'Europe/Kyiv', name: 'Ukraine', flag: '🇺🇦', langs: ['uk'],
    currency: { code: 'UAH', symbol: '₴', name: 'Ukrainian hryvnia' },
    emergency: { general: '112', police: '102', fire: '101', ambulance: '103' },
    power: { volts: '230 V', hz: '50 Hz', plugs: 'C, F' },
    tipping: 'Around 10%.',
    water: 'Bottled water is the safer choice.',
    driving: 'right',
    notes: 'Check your government\'s current travel advice before going.',
  },
];

export const WATCH = {
  IT: [
    'Validate regional train tickets in the green machines before boarding — an unvalidated ticket is a fine, not a warning.',
    'Historic centres are camera-enforced driving zones (ZTL). Fines arrive months later, one per pass.',
    'Restaurants add a per-person cover charge (coperto). It is legal and not a tip.',
    'Standing at the bar costs much less than sitting at a table for the same coffee.',
    'Termini station and busy buses are pickpocket territory. Bag in front, phone away.',
    'Museums often close on Mondays. Book the big ones ahead.',
  ],
  DE: [
    'Plenty of bakeries, bars and kiosks are cash only. Carry notes.',
    'Buy and validate transport tickets before boarding — inspectors are plain-clothed.',
    'Shops shut on Sundays, almost without exception.',
    'Bottle deposit (Pfand) is refunded at supermarket machines. Keep the bottles.',
    'Jaywalking is frowned on and occasionally fined.',
  ],
  PL: [
    'Validate or stamp transport tickets as you board.',
    'Avoid currency exchange at airports and stations — use a kantor in town.',
    'Cards work almost everywhere, but small stalls may not take them.',
  ],
  CZ: [
    'Refuse prices quoted in euros — the rate will be poor.',
    'Avoid street exchange booths advertising "zero commission".',
    'Validate tram and metro tickets in the yellow machines.',
    'Some Prague restaurants near the centre charge tourist prices. Check the menu before sitting.',
  ],
  AT: [
    'Motorways require a vignette sticker bought in advance.',
    'Shops shut on Sundays.',
    'Cash is still expected in smaller places.',
  ],
  FR: [
    'Say bonjour before anything else. It genuinely changes the interaction.',
    'Tap water is free — ask for une carafe d\'eau.',
    'Validate regional train tickets before boarding.',
  ],
  ES: [
    'Lunch runs to 14:00 and dinner past 21:00. Kitchens close between.',
    'Menu del dia at lunch is far cheaper than ordering the same food at night.',
    'Busy Barcelona streets are pickpocket territory.',
  ],
  NL: [
    'Many places take only Maestro or debit, not credit cards.',
    'Bike lanes are roads. Cyclists have priority and will not stop for you.',
  ],
  CH: [
    'Not in the EU — roaming may be charged separately. Check before crossing.',
    'Swiss type J sockets are narrower than type F. Your adapter may not fit.',
    'Everything costs more than you expect. Supermarket lunches help.',
  ],
  GB: [
    'Contactless is universal; cash is nearly optional.',
    'Look right first when crossing.',
    'Service charge is often already on the bill. Do not tip twice.',
  ],
  HR: ['Switched to the euro in 2023 — kuna prices in older guides are dead.'],
  HU: ['Not on the euro. Motorway e-vignette must be bought before you drive.'],
  SE: ['Nearly cashless. Some places refuse cash outright.'],
  DK: ['Largely cashless. 114 is the non-emergency police line.'],
  NO: ['Not in the EU, so roaming rules differ. Very expensive.'],
  BE: ['Dutch north, French south. English is the safe neutral choice.'],
  SK: ['Czech is widely understood, and Polish often is too.'],
  SI: ['Motorways require a vignette.'],
  UA: ['Check your government\'s current travel advice before going.'],
};

export const country = (code) => COUNTRIES.find((c) => c.code === code) || COUNTRIES[0];

// Plug letters worth explaining, since "type F" means nothing on its own.
export const PLUG_NOTES = {
  C: 'two round pins — the common European one',
  E: 'two round pins with a socket hole for the earth pin',
  F: 'two round pins with earth clips on the sides ("Schuko")',
  G: 'three rectangular pins — British only',
  J: 'three round pins in a narrow triangle — Swiss only',
  K: 'two round pins with an earth pin below — Danish (a type F plug fits but does not earth)',
  L: 'three round pins in a line — Italian',
};

// Clothing and shoe sizing. Rough but good enough to try something on.
export const SIZES = {
  shoesWomen: { label: "Shoes (women)", eu: [35, 36, 37, 38, 39, 40, 41, 42], uk: [2.5, 3.5, 4.5, 5, 6, 6.5, 7.5, 8], us: [5, 6, 6.5, 7.5, 8.5, 9, 10, 10.5] },
  shoesMen: { label: 'Shoes (men)', eu: [39, 40, 41, 42, 43, 44, 45, 46], uk: [6, 6.5, 7.5, 8, 9, 9.5, 10.5, 11], us: [7, 7.5, 8.5, 9, 10, 10.5, 11.5, 12] },
  clothesWomen: { label: 'Clothes (women)', eu: [32, 34, 36, 38, 40, 42, 44, 46], uk: [4, 6, 8, 10, 12, 14, 16, 18], us: [0, 2, 4, 6, 8, 10, 12, 14] },
  clothesMen: { label: 'Clothes (men)', eu: [44, 46, 48, 50, 52, 54, 56, 58], uk: [34, 36, 38, 40, 42, 44, 46, 48], us: [34, 36, 38, 40, 42, 44, 46, 48] },
};

// What to actually type into a map search. Searching "pharmacy" in Italy finds
// far less than "farmacia" does, and Rome's drinking fountains are only ever
// tagged "fontanella".
export const NEARBY = [
  { id: 'pharmacy', osm: "[\"amenity\"=\"pharmacy\"]",   icon: '✚',  en: 'Pharmacy',
    terms: { it: 'farmacia', de: 'Apotheke', pl: 'apteka', fr: 'pharmacie', es: 'farmacia', cs: 'lékárna', nl: 'apotheek', sv: 'apotek', uk: 'аптека', en: 'pharmacy' } },
  { id: 'hospital', osm: "[\"amenity\"~\"hospital|clinic\"]",   icon: '⛨',  en: 'Hospital',
    terms: { it: 'ospedale', de: 'Krankenhaus', pl: 'szpital', fr: 'hôpital', es: 'hospital', cs: 'nemocnice', nl: 'ziekenhuis', sv: 'sjukhus', uk: 'лікарня', en: 'hospital' } },
  { id: 'atm', osm: "[\"amenity\"=\"atm\"]",        icon: '▤',  en: 'Cash machine',
    terms: { it: 'bancomat', de: 'Geldautomat', pl: 'bankomat', fr: 'distributeur automatique', es: 'cajero automático', cs: 'bankomat', nl: 'geldautomaat', sv: 'bankomat', uk: 'банкомат', en: 'ATM' } },
  { id: 'supermarket', osm: "[\"shop\"=\"supermarket\"]", icon: '▦', en: 'Supermarket',
    terms: { it: 'supermercato', de: 'Supermarkt', pl: 'supermarket', fr: 'supermarché', es: 'supermercado', cs: 'supermarket', nl: 'supermarkt', sv: 'livsmedelsbutik', uk: 'супермаркет', en: 'supermarket' } },
  { id: 'station', osm: "[\"railway\"=\"station\"]",    icon: '⇄',  en: 'Train station',
    terms: { it: 'stazione ferroviaria', de: 'Bahnhof', pl: 'dworzec kolejowy', fr: 'gare', es: 'estación de tren', cs: 'vlakové nádraží', nl: 'treinstation', sv: 'järnvägsstation', uk: 'залізничний вокзал', en: 'train station' } },
  { id: 'water', osm: "[\"amenity\"=\"drinking_water\"]",      icon: '≈',  en: 'Drinking water',
    terms: { it: 'fontanella', de: 'Trinkbrunnen', pl: 'źródło wody pitnej', fr: 'fontaine à boire', es: 'fuente de agua potable', cs: 'pítko', nl: 'drinkwaterpunt', sv: 'dricksvatten', uk: 'питна вода', en: 'drinking water' } },
  { id: 'toilet', osm: "[\"amenity\"=\"toilets\"]",     icon: '◍',  en: 'Public toilet',
    terms: { it: 'bagno pubblico', de: 'öffentliche Toilette', pl: 'toaleta publiczna', fr: 'toilettes publiques', es: 'baño público', cs: 'veřejné toalety', nl: 'openbaar toilet', sv: 'offentlig toalett', uk: 'громадський туалет', en: 'public toilet' } },
  { id: 'food', osm: "[\"amenity\"~\"restaurant|fast_food\"]",       icon: '◉',  en: 'Somewhere to eat',
    terms: { it: 'trattoria', de: 'Restaurant', pl: 'restauracja', fr: 'restaurant', es: 'restaurante', cs: 'restaurace', nl: 'restaurant', sv: 'restaurang', uk: 'ресторан', en: 'restaurant' } },
  { id: 'police', osm: "[\"amenity\"=\"police\"]",     icon: '★',  en: 'Police station',
    terms: { it: 'questura', de: 'Polizei', pl: 'komisariat policji', fr: 'commissariat', es: 'comisaría', cs: 'policie', nl: 'politiebureau', sv: 'polisstation', uk: 'поліція', en: 'police station' } },
  { id: 'fuel', osm: "[\"amenity\"=\"fuel\"]",       icon: '◈',  en: 'Petrol station',
    terms: { it: 'benzinaio', de: 'Tankstelle', pl: 'stacja benzynowa', fr: 'station-essence', es: 'gasolinera', cs: 'čerpací stanice', nl: 'tankstation', sv: 'bensinstation', uk: 'заправка', en: 'petrol station' } },
];

export const nearbyTerm = (item, langCode) => item.terms[langCode] || item.terms.en;

// Getting around: the operator names you need to search for, and the rule that
// catches people out. Offline.
export const TRANSIT = {
  IT: {
    rail: 'Trenitalia runs regional trains and the Frecce fast services; Italo is a separate private operator on the same fast lines.',
    rule: 'Regional tickets must be validated in the green machines on the platform before boarding. Fast trains booked for a specific seat do not need it.',
    city: 'Buy bus and metro tickets at a tabaccheria, newsstand or machine before boarding, then stamp them on board.',
    taxi: 'Use the official white taxis at ranks. Rome Fiumicino to the centre is a fixed fare — insist on it rather than the meter.',
  },
  DE: {
    rail: 'Deutsche Bahn (DB) for everything; regional services are RE and RB.',
    rule: 'Online and app tickets need no validation. Paper tickets from a machine usually do — check the ticket.',
    city: 'Buy before boarding. Inspectors are in plain clothes and the fine is immediate.',
    taxi: 'Metered and honest. Ordering by app is normal.',
  },
  PL: {
    rail: 'PKP Intercity for long distance, regional operators like Polregio and Koleje Mazowieckie locally.',
    rule: 'Validate or have the conductor stamp a paper ticket. App tickets are fine as they are.',
    city: 'Buy from a kiosk, machine or app, then validate on board.',
    taxi: 'Use an app or an official rank. Avoid unmarked cars outside stations.',
  },
  CZ: {
    rail: 'České dráhy (ČD) plus RegioJet and Leo Express on some routes, often cheaper.',
    rule: 'Validate tram and metro tickets in the yellow machines as you board.',
    city: 'Tickets are time-based. Buy the right duration for your journey.',
    taxi: 'Use an app. Prague street taxis have a long-standing reputation for overcharging.',
  },
  FR: {
    rail: 'SNCF: TGV and Ouigo for fast, TER for regional.',
    rule: 'Validate (composter) regional paper tickets in the yellow machines before boarding.',
    city: 'Paris carnets are gone — use a Navigo Easy card or contactless.',
    taxi: 'Metered. Airport runs from Paris are fixed-fare by zone.',
  },
  ES: {
    rail: 'Renfe, with AVE for high speed. Iryo and Ouigo compete on the main lines.',
    rule: 'Long-distance tickets are seat-specific and scanned at a gate. Cercanías commuter tickets are validated at the barrier.',
    city: 'Metro cards are usually rechargeable and shared per city.',
    taxi: 'Metered, with fixed airport fares in Madrid and Barcelona.',
  },
  NL: {
    rail: 'NS runs almost everything.',
    rule: 'Check in AND check out with your card at the gates or posts. Forgetting to check out charges you the maximum fare.',
    city: 'Contactless bank cards work on most trains, trams and buses now.',
    taxi: 'Expensive. Trams and bikes are better.',
  },
  AT: {
    rail: 'ÖBB, with Westbahn competing on the Vienna–Salzburg line.',
    rule: 'App and online tickets need no validation.',
    city: 'Vienna sells time-based passes. Inspectors are frequent and plain-clothed.',
    taxi: 'Metered. Ordering by app is normal.',
  },
  CH: {
    rail: 'SBB/CFF/FFS. Superb and expensive — look at a Half Fare Card if staying a while.',
    rule: 'No validation needed. Ticketless travel carries a heavy fine.',
    city: 'City passes usually cover trams, buses and boats together.',
    taxi: 'Very expensive. Use the train.',
  },
  GB: {
    rail: 'Many operators, one ticketing system. Book ahead for anything long distance — walk-up fares are punishing.',
    rule: 'No validation, but the ticket must match the operator and time band.',
    city: 'In London just tap a contactless card in and out; the daily cap is applied automatically.',
    taxi: 'Black cabs are metered. Minicabs must be booked, never hailed.',
  },
};

export const transit = (code) => TRANSIT[code] || null;

// "Where do I buy the thing I'd get at home?" Written from a Polish starting
// point, since that is where the chains are familiar from.
//
// General guidance: chains open, close and rebrand, so treat it as a starting
// point for a map search rather than gospel.
export const SHOPS = [
  {
    id: 'electronics',
    osm: "[\"shop\"~\"electronics|appliance\"]",
    find: {"IT": "MediaWorld", "DE": "MediaMarkt", "CZ": "Alza", "AT": "MediaMarkt", "FR": "Fnac", "ES": "MediaMarkt", "NL": "MediaMarkt", "GB": "Currys"}, label: 'Electronics and appliances',
    pl: 'Media Markt, Media Expert, x-kom, RTV Euro AGD',
    by: {
      IT: 'MediaWorld — literally Media Markt under its Italian name, same group. Also Unieuro, Euronics, Trony.',
      DE: 'MediaMarkt and Saturn (same owner). Expert and Euronics locally.',
      CZ: 'Alza is the big one, plus Datart and Electro World.',
      AT: 'MediaMarkt and Saturn.',
      FR: 'Fnac, Darty and Boulanger. No MediaMarkt in France.',
      ES: 'MediaMarkt, Worten, and PcComponentes online.',
      NL: 'MediaMarkt, Coolblue and BCC.',
      GB: 'Currys, and Argos for pick-up-today.',
    },
  },
  {
    id: 'groceries',
    osm: "[\"shop\"~\"supermarket|convenience\"]",
    find: {"IT": "supermercato", "DE": "Supermarkt", "CZ": "supermarket", "AT": "Billa", "FR": "supermarch\u00e9", "ES": "Mercadona", "NL": "Albert Heijn", "GB": "Tesco"}, label: 'Big supermarket',
    pl: 'Biedronka, Lidl, Kaufland, Carrefour, Auchan',
    by: {
      IT: 'Esselunga, Conad, Coop, Carrefour, Pam. Eurospin and MD are the cheap ones; Lidl is here too.',
      DE: 'Rewe, Edeka, Kaufland. Aldi, Lidl, Netto and Penny for cheap.',
      CZ: 'Albert, Billa, Kaufland, Tesco. Lidl and Penny for cheap.',
      AT: 'Billa and Spar. Hofer is Aldi under another name; Lidl and Penny too.',
      FR: 'Carrefour, Leclerc, Intermarché, Auchan. Lidl and Aldi for cheap.',
      ES: 'Mercadona above all, then Carrefour, Dia, Alcampo.',
      NL: 'Albert Heijn, Jumbo, Plus. Lidl and Aldi for cheap.',
      GB: "Tesco, Sainsbury's, Asda, Morrisons. Aldi and Lidl for cheap.",
    },
  },
  {
    id: 'convenience',
    osm: "[\"shop\"=\"convenience\"]",
    find: {"IT": null, "DE": null, "CZ": "ve\u010derka", "AT": null, "FR": "Carrefour City", "ES": null, "NL": "AH to go", "GB": "Tesco Express"}, label: 'Corner shop / Żabka',
    pl: 'Żabka, Carrefour Express',
    by: {
      IT: 'Nothing really matches Żabka. A bar does coffee and snacks, a tabaccheria does tickets, stamps and top-ups, and a small alimentari does groceries. Supermarkets often shut by 20:00 and on Sunday afternoons.',
      DE: 'Petrol station shops and Spätkauf/Kiosk in bigger cities. Supermarkets shut on Sundays entirely.',
      CZ: 'Small večerka shops, plus Žabka — the same brand operates here.',
      AT: 'Station shops at main railway stations are the Sunday option.',
      FR: 'Carrefour City and Franprix in towns. Boulangeries open early.',
      ES: 'Small alimentación shops, often open late.',
      NL: 'AH to go and station shops.',
      GB: 'Tesco Express, Sainsbury\'s Local, Co-op. Open late and on Sundays.',
    },
  },
  {
    id: 'drugstore',
    osm: "[\"shop\"~\"chemist|cosmetics\"]",
    find: {"IT": "Acqua & Sapone", "DE": "dm Drogerie", "CZ": "Rossmann", "AT": "dm Drogerie", "FR": "parapharmacie", "ES": "Druni", "NL": "Kruidvat", "GB": "Boots"}, label: 'Drugstore / cosmetics',
    pl: 'Rossmann, Hebe, Super-Pharm',
    by: {
      IT: 'Acqua & Sapone and Tigotà. Note that actual medicine is only sold in a farmacia or parafarmacia, not here.',
      DE: 'dm and Rossmann — Rossmann is the same chain you know.',
      CZ: 'Rossmann, dm and Teta.',
      AT: 'dm and Bipa.',
      FR: 'Parapharmacie counters, plus Marionnaud and Nocibé for cosmetics.',
      ES: 'Primor and Druni.',
      NL: 'Kruidvat and Etos.',
      GB: 'Boots and Superdrug.',
    },
  },
  {
    id: 'pharmacy',
    osm: "[\"amenity\"=\"pharmacy\"]",
    find: {"IT": "farmacia", "DE": "Apotheke", "CZ": "l\u00e9k\u00e1rna", "AT": "Apotheke", "FR": "pharmacie", "ES": "farmacia", "NL": "apotheek", "GB": "pharmacy"}, label: 'Pharmacy',
    pl: 'Apteka',
    by: {
      IT: 'Farmacia — look for the green cross. A parafarmacia sells non-prescription items only. Painkillers are not in supermarkets here.',
      DE: 'Apotheke, red A sign. Even ibuprofen is pharmacy-only.',
      CZ: 'Lékárna.',
      AT: 'Apotheke.',
      FR: 'Pharmacie, green cross.',
      ES: 'Farmacia, green cross.',
      NL: 'Apotheek, though Kruidvat sells basic painkillers.',
      GB: 'Boots or any pharmacy counter; supermarkets sell basics too.',
    },
  },
  {
    id: 'diy',
    osm: "[\"shop\"~\"doityourself|hardware|trade\"]",
    find: {"IT": "Leroy Merlin", "DE": "Baumarkt", "CZ": "Hornbach", "AT": "Bauhaus", "FR": "Leroy Merlin", "ES": "Leroy Merlin", "NL": "Gamma", "GB": "B&Q"}, label: 'DIY and hardware',
    pl: 'Castorama, Leroy Merlin, OBI',
    by: {
      IT: 'Leroy Merlin, OBI, Bricocenter, Bricoman.',
      DE: 'Bauhaus, OBI, Hornbach, Toom.',
      CZ: 'Hornbach, OBI, Bauhaus.',
      AT: 'Bauhaus, OBI, Hornbach, Lagerhaus.',
      FR: 'Leroy Merlin, Castorama, Brico Dépôt.',
      ES: 'Leroy Merlin, Bauhaus, Bricomart.',
      NL: 'Praxis, Gamma, Karwei.',
      GB: 'B&Q, Wickes, and Screwfix for trade.',
    },
  },
  {
    id: 'sports',
    osm: "[\"shop\"=\"sports\"]",
    find: {"IT": "Decathlon", "DE": "Decathlon", "CZ": "Decathlon", "AT": "Hervis", "FR": "Decathlon", "ES": "Decathlon", "NL": "Decathlon", "GB": "Decathlon"}, label: 'Sports gear',
    pl: 'Decathlon, Martes Sport, Sklep Sportowy',
    by: {
      IT: 'Decathlon is here, plus Cisalfa Sport.',
      DE: 'Decathlon, Intersport, SportScheck.',
      CZ: 'Decathlon, Sportisimo, A3 Sport.',
      AT: 'Hervis, Intersport, Decathlon.',
      FR: 'Decathlon — it is French, so they are everywhere. Also Intersport, Go Sport.',
      ES: 'Decathlon, Sprinter.',
      NL: 'Decathlon, Intersport, Perry Sport.',
      GB: 'Decathlon, Sports Direct.',
    },
  },
  {
    id: 'cheapclothes',
    osm: "[\"shop\"=\"clothes\"]",
    find: {"IT": "Kiabi", "DE": "KiK", "CZ": "Pepco", "AT": "KiK", "FR": "Kiabi", "ES": "Primark", "NL": "Action", "GB": "Primark"}, label: 'Cheap clothes',
    pl: 'Pepco, Sinsay, House, KiK',
    by: {
      IT: 'Kiabi, OVS, Terranova, Primark in bigger cities.',
      DE: 'KiK, Primark, Takko, C&A.',
      CZ: 'Pepco, KiK, Takko — Pepco is the same chain.',
      AT: 'KiK, Primark, C&A.',
      FR: 'Kiabi, Primark, Gémo.',
      ES: 'Lefties (Inditex\'s cheap line), Primark.',
      NL: 'Zeeman, Action, Primark.',
      GB: 'Primark above all, then Matalan.',
    },
  },
  {
    id: 'parcels',
    osm: "[\"amenity\"~\"post_office|parcel_locker\"]",
    find: {"IT": "Poste Italiane", "DE": "DHL Packstation", "CZ": "Z\u00e1silkovna", "AT": "Post Filiale", "FR": "Point Relais", "ES": "Correos", "NL": "PostNL punt", "GB": "Post Office"}, label: 'Parcel lockers and post',
    pl: 'InPost Paczkomat, Poczta Polska, DPD',
    by: {
      IT: 'Poste Italiane, Amazon Locker, and InPost lockers in the north.',
      DE: 'DHL Packstation is the equivalent, plus Hermes shops.',
      CZ: 'Zásilkovna and Balíkovna are the InPost equivalents, plus PPL.',
      AT: 'Post Empfangsbox and post office branches.',
      FR: 'Mondial Relay and Point Relais pick-up points.',
      ES: 'Correos, plus InPost lockers in cities.',
      NL: 'PostNL points, usually inside a supermarket.',
      GB: 'InPost UK lockers and Royal Mail.',
    },
  },
  {
    id: 'sim',
    osm: "[\"shop\"=\"mobile_phone\"]",
    find: {"IT": "TIM", "DE": "Telekom Shop", "CZ": "O2", "AT": "A1 Shop", "FR": "Orange", "ES": "Movistar", "NL": "KPN", "GB": "EE"}, label: 'SIM and mobile data',
    pl: 'Orange, Play, Plus, T-Mobile',
    by: {
      IT: 'TIM, Vodafone, WindTre, plus cheaper Iliad, Ho. and Very Mobile. A Polish SIM already roams here at domestic rates, so only bother if your allowance is spent.',
      DE: 'Telekom, Vodafone, O2, and Aldi Talk for cheap prepaid.',
      CZ: 'O2, T-Mobile, Vodafone.',
      AT: 'A1, Magenta, Drei.',
      FR: 'Orange, SFR, Bouygues, and Free for cheap.',
      ES: 'Movistar, Vodafone, Orange, Yoigo.',
      NL: 'KPN, Vodafone, Odido.',
      GB: 'EE, O2, Vodafone, Three, and giffgaff for cheap. Outside the EEA, so roaming may cost.',
    },
  },
  {
    id: 'online',
    osm: null,
    find: {"IT": null, "DE": null, "CZ": null, "AT": null, "FR": null, "ES": null, "NL": null, "GB": null}, label: 'Buying online / secondhand',
    pl: 'Allegro, OLX, Vinted',
    by: {
      IT: 'Amazon.it for new, Subito.it for secondhand — Subito is the OLX equivalent. Vinted works here too.',
      DE: 'Amazon.de, and Kleinanzeigen for secondhand.',
      CZ: 'Alza, Aukro, and Bazoš for secondhand.',
      AT: 'Amazon.at and willhaben.',
      FR: 'Amazon.fr and Leboncoin.',
      ES: 'Amazon.es, Wallapop, Milanuncios.',
      NL: 'bol.com and Marktplaats.',
      GB: 'Amazon.co.uk, eBay, Gumtree, Vinted.',
    },
  },
];

export const shopsFor = (code) => SHOPS.map((s) => ({
  ...s,
  local: s.by[code] || null,
  // Explicit search term, or null where the category has no local counterpart
  // (nobody sells "an online marketplace" on a street corner).
  search: (s.find && s.find[code]) || null,
  osm: s.osm || null,
}));
export const hasShops = (code) => SHOPS.some((s) => s.by[code]);
