// Travel phrases, ordered [category, en, de, pl, it]. Fully offline.
// Italian was added because Italy fell through to a translation memory that
// answered "Goodbye" with "Addio" — which means farewell, not see you later.
// Lifted from the standalone phrasebook so there is a single copy to maintain.

export const PHRASE_CATS = [
  { id: 'saved',   label: 'Saved' },
  { id: 'all',     label: 'All' },
  { id: 'basics',  label: 'Basics' },
  { id: 'going',   label: 'Getting around' },
  { id: 'food',    label: 'Food' },
  { id: 'money',   label: 'Shopping' },
  { id: 'sleep',   label: 'Sleeping' },
  { id: 'trouble', label: 'Trouble' },
  { id: 'health',  label: 'Health' },
  { id: 'when',    label: 'Numbers & time' },
];

// Shown big on the emergency card, in the local language.
export const EMERGENCY_PHRASES = [
  'I need help',
  'I need a doctor',
  'Please call an ambulance',
  'Please call the police',
  "I'm allergic to penicillin",
  'I have asthma',
  'I lost my passport',
  'I want to call my parents',
];

export const PHRASES = [
  ['basics','Hello','Hallo','Cześć', 'Ciao'],
  ['basics','Good morning','Guten Morgen','Dzień dobry', 'Buongiorno'],
  ['basics','Good evening','Guten Abend','Dobry wieczór', 'Buonasera'],
  ['basics','Goodbye','Auf Wiedersehen','Do widzenia', 'Arrivederci'],
  ['basics','Please','Bitte','Proszę', 'Per favore'],
  ['basics','Thank you','Danke','Dziękuję', 'Grazie'],
  ['basics','Thank you very much','Vielen Dank','Dziękuję bardzo', 'Grazie mille'],
  ['basics',"You're welcome",'Gern geschehen','Nie ma za co', 'Prego'],
  ['basics','Excuse me','Entschuldigung','Przepraszam', 'Mi scusi'],
  ['basics',"I'm sorry",'Es tut mir leid','Bardzo mi przykro', 'Mi dispiace'],
  ['basics','Yes','Ja','Tak', 'Sì'],
  ['basics','No','Nein','Nie', 'No'],
  ['basics','I understand','Ich verstehe','Rozumiem', 'Capisco'],
  ['basics',"I don't understand",'Ich verstehe nicht','Nie rozumiem', 'Non capisco'],
  ['basics','Do you speak English?','Sprechen Sie Englisch?','Czy mówi pan po angielsku?', 'Parla inglese?'],
  ['basics',"I don't speak German",'Ich spreche kein Deutsch','Nie mówię po niemiecku', 'Non parlo tedesco'],
  ['basics','Could you repeat that?','Können Sie das wiederholen?','Czy może pan powtórzyć?', 'Può ripetere, per favore?'],
  ['basics','Please speak slowly','Sprechen Sie bitte langsam','Proszę mówić wolniej', 'Parli più lentamente, per favore'],
  ['basics','Could you write it down?','Können Sie das aufschreiben?','Czy może pan to napisać?', 'Può scriverlo?'],
  ['basics','My name is…','Ich heiße…','Nazywam się…', 'Mi chiamo…'],
  ['basics','Nice to meet you','Freut mich','Miło mi', 'Piacere'],
  ['basics','How are you?','Wie geht es Ihnen?','Jak się pan miewa?', 'Come sta?'],
  ['basics',"I'm from Poland",'Ich komme aus Polen','Jestem z Polski', 'Vengo dalla Polonia'],
  ['basics','Can you help me?','Können Sie mir helfen?','Czy może mi pan pomóc?', 'Può aiutarmi?'],
  ['going','Where is…?','Wo ist…?','Gdzie jest…?', 'Dov’è…?'],
  ['going','Where is the train station?','Wo ist der Bahnhof?','Gdzie jest dworzec kolejowy?', 'Dov’è la stazione ferroviaria?'],
  ['going','Where is the bus stop?','Wo ist die Bushaltestelle?','Gdzie jest przystanek autobusowy?', 'Dov’è la fermata dell’autobus?'],
  ['going','Where is the airport?','Wo ist der Flughafen?','Gdzie jest lotnisko?', 'Dov’è l’aeroporto?'],
  ['going','Where is the toilet?','Wo ist die Toilette?','Gdzie jest toaleta?', 'Dov’è il bagno?'],
  ['going','How do I get to…?','Wie komme ich nach…?','Jak dojadę do…?', 'Come arrivo a…?'],
  ['going','Is it far?','Ist es weit?','Czy to daleko?', 'È lontano?'],
  ['going','Can I walk there?','Kann ich zu Fuß gehen?','Czy mogę tam dojść pieszo?', 'Posso andarci a piedi?'],
  ['going','Left','Links','W lewo', 'A sinistra'],
  ['going','Right','Rechts','W prawo', 'A destra'],
  ['going','Straight ahead','Geradeaus','Prosto', 'Sempre dritto'],
  ['going','Show me on the map, please','Zeigen Sie es mir bitte auf der Karte','Proszę pokazać mi na mapie', 'Me lo mostri sulla mappa, per favore'],
  ['going','One ticket to…, please','Eine Fahrkarte nach…, bitte','Jeden bilet do…, proszę', 'Un biglietto per…, per favore'],
  ['going','Two tickets, please','Zwei Fahrkarten, bitte','Dwa bilety, proszę', 'Due biglietti, per favore'],
  ['going','A return ticket','Eine Rückfahrkarte','Bilet powrotny', 'Un biglietto di andata e ritorno'],
  ['going','When does the train leave?','Wann fährt der Zug ab?','O której odjeżdża pociąg?', 'A che ora parte il treno?'],
  ['going','Which platform?','Welches Gleis?','Który peron?', 'Quale binario?'],
  ['going','Does this bus go to…?','Fährt dieser Bus nach…?','Czy ten autobus jedzie do…?', 'Questo autobus va a…?'],
  ['going','Is this seat free?','Ist dieser Platz frei?','Czy to miejsce jest wolne?', 'È libero questo posto?'],
  ['going','I missed my train','Ich habe meinen Zug verpasst','Spóźniłem się na pociąg', 'Ho perso il treno'],
  ['going','Please stop here','Halten Sie hier, bitte','Proszę się tu zatrzymać', 'Si fermi qui, per favore'],
  ['going','How much is the fare?','Was kostet die Fahrt?','Ile kosztuje przejazd?', 'Quanto costa il biglietto?'],
  ['food','A table for two, please','Einen Tisch für zwei, bitte','Stolik dla dwóch osób, proszę', 'Un tavolo per due, per favore'],
  ['food','The menu, please','Die Speisekarte, bitte','Poproszę menu', 'Il menù, per favore'],
  ['food','What do you recommend?','Was empfehlen Sie?','Co pan poleca?', 'Cosa mi consiglia?'],
  ['food',"I'd like…",'Ich hätte gern…','Poproszę…', 'Vorrei…'],
  ['food','Water, please','Wasser, bitte','Poproszę wodę', 'Dell’acqua, per favore'],
  ['food','A coffee','Einen Kaffee','Kawę', 'Un caffè'],
  ['food','A beer','Ein Bier','Piwo', 'Una birra'],
  ['food',"I'm vegetarian",'Ich bin Vegetarier','Jestem wegetarianinem', 'Sono vegetariano'],
  ['food','Without meat, please','Ohne Fleisch, bitte','Bez mięsa, proszę', 'Senza carne, per favore'],
  ['food',"I'm allergic to nuts",'Ich bin allergisch gegen Nüsse','Mam alergię na orzechy', 'Sono allergico alla frutta secca'],
  ['food','Does this contain…?','Enthält das…?','Czy to zawiera…?', 'Contiene…?'],
  ['food','The bill, please','Die Rechnung, bitte','Poproszę rachunek', 'Il conto, per favore'],
  ['food','Can I pay by card?','Kann ich mit Karte zahlen?','Czy mogę zapłacić kartą?', 'Posso pagare con la carta?'],
  ['food','To take away, please','Zum Mitnehmen, bitte','Na wynos, proszę', 'Da portare via, per favore'],
  ['food','It was delicious','Es war lecker','Było pyszne', 'Era squisito'],
  ['money','How much does it cost?','Was kostet das?','Ile to kosztuje?', 'Quanto costa?'],
  ['money',"That's too expensive",'Das ist zu teuer','To za drogo', 'È troppo caro'],
  ['money',"I'm just looking",'Ich schaue mich nur um','Tylko oglądam', 'Sto solo guardando'],
  ['money',"I'll take it",'Ich nehme es','Wezmę to', 'Lo prendo'],
  ['money','Do you have another size?','Haben Sie eine andere Größe?','Czy jest inny rozmiar?', 'Avete un’altra taglia?'],
  ['money','Where is an ATM?','Wo ist ein Geldautomat?','Gdzie jest bankomat?', 'Dov’è un bancomat?'],
  ['money','Do you accept cards?','Nehmen Sie Karten?','Czy przyjmujecie karty?', 'Accettate carte?'],
  ['money','A receipt, please','Eine Quittung, bitte','Poproszę paragon', 'Lo scontrino, per favore'],
  ['money','Is there Wi-Fi here?','Gibt es hier WLAN?','Czy jest tu Wi-Fi?', 'C’è il Wi-Fi qui?'],
  ['money','What is the Wi-Fi password?','Wie lautet das WLAN-Passwort?','Jakie jest hasło do Wi-Fi?', 'Qual è la password del Wi-Fi?'],
  ['sleep','I have a reservation','Ich habe eine Reservierung','Mam rezerwację', 'Ho una prenotazione'],
  ['sleep','Do you have a room free?','Haben Sie ein Zimmer frei?','Czy są wolne pokoje?', 'Avete una camera libera?'],
  ['sleep','For one night','Für eine Nacht','Na jedną noc', 'Per una notte'],
  ['sleep','What time is check-out?','Wann ist der Check-out?','O której jest wymeldowanie?', 'A che ora è il check-out?'],
  ['sleep','Can I leave my luggage here?','Kann ich mein Gepäck hier lassen?','Czy mogę tu zostawić bagaż?', 'Posso lasciare qui i bagagli?'],
  ['sleep','The room is too cold','Das Zimmer ist zu kalt','W pokoju jest za zimno', 'In camera fa troppo freddo'],
  ['sleep','There is no hot water','Es gibt kein warmes Wasser','Nie ma ciepłej wody', 'Non c’è acqua calda'],
  ['sleep','Where can I charge my phone?','Wo kann ich mein Handy aufladen?','Gdzie mogę naładować telefon?', 'Dove posso ricaricare il telefono?'],
  ['trouble','Help!','Hilfe!','Pomocy!', 'Aiuto!'],
  ['trouble','I need help','Ich brauche Hilfe','Potrzebuję pomocy', 'Ho bisogno di aiuto'],
  ['trouble',"I'm lost",'Ich habe mich verlaufen','Zgubiłem się', 'Mi sono perso'],
  ['trouble','I lost my passport','Ich habe meinen Pass verloren','Zgubiłem paszport', 'Ho perso il passaporto'],
  ['trouble','My phone was stolen','Mein Handy wurde gestohlen','Ukradziono mi telefon', 'Mi hanno rubato il telefono'],
  ['trouble','Please call the police','Rufen Sie bitte die Polizei','Proszę wezwać policję', 'Chiami la polizia, per favore'],
  ['trouble','Where is the Polish embassy?','Wo ist die polnische Botschaft?','Gdzie jest polska ambasada?', 'Dov’è l’ambasciata polacca?'],
  ['trouble','Please leave me alone','Lassen Sie mich bitte in Ruhe','Proszę zostawić mnie w spokoju', 'Mi lasci in pace, per favore'],
  ['trouble','I want to call my parents','Ich möchte meine Eltern anrufen','Chcę zadzwonić do rodziców', 'Voglio chiamare i miei genitori'],
  ['health','I need a doctor','Ich brauche einen Arzt','Potrzebuję lekarza', 'Ho bisogno di un medico'],
  ['health','Please call an ambulance','Rufen Sie bitte einen Krankenwagen','Proszę wezwać karetkę', 'Chiami un’ambulanza, per favore'],
  ['health','Where is the pharmacy?','Wo ist die Apotheke?','Gdzie jest apteka?', 'Dov’è la farmacia?'],
  ['health','It hurts here','Es tut hier weh','Boli mnie tutaj', 'Mi fa male qui'],
  ['health','I have a headache','Ich habe Kopfschmerzen','Boli mnie głowa', 'Ho mal di testa'],
  ['health','I have a fever','Ich habe Fieber','Mam gorączkę', 'Ho la febbre'],
  ['health',"I'm allergic to penicillin",'Ich bin allergisch gegen Penizillin','Mam alergię na penicylinę', 'Sono allergico alla penicillina'],
  ['health','I have asthma','Ich habe Asthma','Mam astmę', 'Ho l’asma'],
  ['health','Something for a cold, please','Etwas gegen Erkältung, bitte','Coś na przeziębienie, proszę', 'Qualcosa per il raffreddore, per favore'],
  ['health','Painkillers','Schmerzmittel','Środki przeciwbólowe', 'Antidolorifici'],
  ['when','What time is it?','Wie spät ist es?','Która godzina?', 'Che ore sono?'],
  ['when','At what time?','Um wie viel Uhr?','O której godzinie?', 'A che ora?'],
  ['when','Today','Heute','Dziś', 'Oggi'],
  ['when','Tomorrow','Morgen','Jutro', 'Domani'],
  ['when','Yesterday','Gestern','Wczoraj', 'Ieri'],
  ['when','Now','Jetzt','Teraz', 'Adesso'],
  ['when','Later','Später','Później', 'Più tardi'],
  ['when','Open','Geöffnet','Otwarte', 'Aperto'],
  ['when','Closed','Geschlossen','Zamknięte', 'Chiuso'],
  ['when','One','Eins','Jeden', 'Uno'],
  ['when','Two','Zwei','Dwa', 'Due'],
  ['when','Three','Drei','Trzy', 'Tre'],
  ['when','Four','Vier','Cztery', 'Quattro'],
  ['when','Five','Fünf','Pięć', 'Cinque'],
  ['when','Six','Sechs','Sześć', 'Sei'],
  ['when','Seven','Sieben','Siedem', 'Sette'],
  ['when','Eight','Acht','Osiem', 'Otto'],
  ['when','Nine','Neun','Dziewięć', 'Nove'],
  ['when','Ten','Zehn','Dziesięć', 'Dieci'],
  ['when','Twenty','Zwanzig','Dwadzieścia', 'Venti'],
  ['when','Fifty','Fünfzig','Pięćdziesiąt', 'Cinquanta'],
  ['when','One hundred','Hundert','Sto', 'Cento']
];

export const PHRASE_COL = { en: 1, de: 2, pl: 3, it: 4 };
